#!/usr/bin/env bash
# Ensures Nginx is installed and running, listening on port 80
which nginx > /dev/null 2>&1 || apt-get install -y nginx > /dev/null 2>&1
pkill -9 nginx 2>/dev/null
/etc/init.d/nginx start
sleep 2
