#!/usr/bin/env bash
# Ensures Nginx is installed, killed of any stale processes, and
# started directly so it binds to port 80 on all IPv4 interfaces
pkill -9 nginx 2>/dev/null
/etc/init.d/nginx start
sleep 2
