#!/usr/bin/env bash
# Installs and configures nginx to serve a page containing "Holberton School"
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
