#!/usr/bin/env bash
# Installs and configures nginx to serve a page containing "Holberton School"

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

apt-get -y update
apt-get -y install nginx

mkdir -p /usr/share/nginx/html
echo "Holberton School" > /usr/share/nginx/html/index.html

service nginx start || service nginx restart
